version: 2

jobs:
   build:
     machine: true
     steps:
       - checkout
       - run: docker version
       - run: docker info
       - run: sudo curl --output /tmp/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
       - run: sudo chmod ugo+x /tmp/phantomjs
       - run: sudo ln -sf /tmp/phantomjs /usr/local/bin/phantomjs
       - run: bundle install
       - run: sudo bundle exec rspec
