version: 2

jobs:
   build:
     # machine: true
     docker:
       - image: circleci/ruby:2.4.1
     steps:
       - checkout
       - setup_remote_docker:
           version: 17.05.0-ce
       - run: docker version
       - run: docker info
       # - run: bundle install
       # - run: bundle exec rspec
